### ISSUE TITLE
Data connector should be self-signed

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi#17]
Going through the PowerBI docs I discovered a way to not have to lower PowerBI security settings in order to get the Speckle data connector to load: **self-signing**

https://learn.microsoft.com/en-us/power-query/handlingconnectorsigning

Seems rather straight forward as it already uses a `pfx` cert, which we have for other CI stuff.

**Comment by AlanRynne** [comment]
Reading up on this, signing alone is not going to cut it. It also requires adding the signature thumbprint onto a specific registry key.

This is not a deal breaker, but it means that for a normal user to benefit from this, we're going to have to create an InnoSetup installer that deals with copying the connector and adding the thumbprint to the registry key.

Slightly bigger task than I originally thought, but not a deal breaker.

**Comment by AlanRynne** [comment]
I've actually got everything needed in place to do this (including the super preliminary installer).

This would not only ease the pain on the current installing process for the data connector, it would also allow them to not lower the security of their PowerBI env by allowing **all** 3rd party connectors

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
