### ISSUE TITLE
Investigate the use of `NavigationTable` in our connector.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi#25]
Navigation Tables display a nicer UI to the end-user to fetch the information they require from a specific source.

This may prove useful in many ways:

- Displaying different types of data inside a stream, such as a comments table, or a stream details table, along side the actual data to be fetched.
- Structuring a commit object to display it's inner structure in a user friendly way. Would depend on #22 
- Navigation Tables have delayed execution (it would seem) so we could benefit from not fetching all objects at once, making the experience more Snappy

See: https://learn.microsoft.com/en-us/power-query/handlingnavigationtables

**Comment by AlanRynne** [comment]
Ok so navigation tables are not the magical solution I was hoping for, but **they will be useful** for sure.

They are used to display different tables (related or not between them) coming from a specific data source.

In our case, it could be used to display different info about a stream that is not strictly geometric:

- Comments
- Branches
- Collaborators
- Commits

Which would then lead to eventually displaying our current objects table, but in a more organised way.

This would be consider a new feature, and not a critical one at that, since starting on 0.0.14 users can make their own queries.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
