### ISSUE TITLE
Use `Table.View` instead of returning raw tables

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi#32]
`Table.View` is, in essence, an object that behaves like a table but is a collection on functions that get called by `PowerQuery`.

This has the advantage of allowing us to implement `query folding` i.e. allowing power query to essentially create queries of our graphql api with PowerQuery code.

This looks super powerful, specially when pulling an objects `children`, that has sorting, filtering and querying capabilities, as well as pagination.

All this could have a significant performance improvement in how different operations work, but can also lead to performance hits if not implemented correctly.

See https://learn.microsoft.com/en-us/power-query/samples/trippin/10-tableview1/readme#using-tableview

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
