### ISSUE TITLE
Community Reports Edition

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-powerbi#40]
Tracking here a few community-reported bugs so we remember to investigate & reply:

- https://speckle.community/t/powerbi-published-report/5114/8
- https://speckle.community/t/power-bi-connector-not-showing-up/5235/3
- https://speckle.community/t/power-bi-loading-issues-of-3d-model/5418/7
- https://speckle.community/t/speckle-power-bi-colours-not-matching/5370/2

**Comment by AlanRynne** [comment]
All these have been solved. (except for the Connector not showing up, which I'm opening a new ticket to track it separately). Will link it here once done.
