### ISSUE TITLE
Viewer improvements

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-powerbi#44]
Not sure what's possible, but tracking these here:
- [x] https://www.notion.so/speckle/Viewer-can-t-load-model-7a14a593e4104da19f784921cac58538
- [x] https://www.notion.so/speckle/3D-viewer-support-views-1ae4dba114ed4470850610c27d60b110?pvs=4
- [x] https://www.notion.so/speckle/3D-viewer-include-section-box-12c2f0fe9a464ac3be2d2bd959401a6d?pvs=4

**Comment by AlanRynne** [comment]
Closing these as they're tracked in the visuals repo individually (and already been done! 🙌🏼)
