### ISSUE TITLE
PowerBi Data Connector not showing up

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi#45]
From the forum: https://speckle.community/t/power-bi-connector-not-showing-up/5235/3

Originally tracked in #40 

Following Microsoft's own directions doesn't seem to work in all cases. This may be related to user setup, but I've found nothing to indicate this could be the case.

More investigation may be needed, but I feel like our hands may be tied on this one. If Microsoft's own instructions don't do the trick there's little that can be done on our side.

**Comment by hymak** [comment]
Got same issue here.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
