### ISSUE TITLE
Empty visual after feilds have been added. 

### ISSUE THREAD

**Issue by Gitkicked** [specklesystems/speckle-powerbi#66]
Hi, 

I followed the online tutorial. Seems like a field may be missing from the .pbiz file as after I have loaded my data and populated the field to the visual nothing populates the viewer. I can see the rooms hosted on the speckle server. 

![Speckel Room Error](https://github.com/specklesystems/speckle-powerbi/assets/134450805/6efdcf0b-c5a3-4de0-a6b2-4ef502d1015f)

**Comment by bimgeek** [comment]
Hey @Gitkicked ,

Our 3D visual currently only supports link-shareable models. This is a known limitation and we're trying to figure it out. Take a look at the below tutorial:

https://youtu.be/brQAkXhoT5Y?si=W6iibaQOo7viQL24

Next time you face a problem, please report at speckle.community as we're usually hanging out there.
